import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

const iconsDir = path.join(rootDir, 'node_modules', '@material-symbols-svg', 'react', 'dist', 'icons');
const metadataFile = path.join(rootDir, 'node_modules', '@material-symbols-svg', 'react', 'dist', 'metadata', 'icon-index.json');
const registryFile = path.join(rootDir, 'src', 'lib', 'icons', 'registry.ts');
const loaderFile = path.join(rootDir, 'src', 'lib', 'icons', 'loader.ts');

function toPascalCase(slug) {
  return slug.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');
}

function toTitleCase(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

async function generate() {
  if (!fs.existsSync(iconsDir)) {
    console.error('Icons directory not found. Please run npm install.');
    process.exit(1);
  }

  let metadata = {};
  if (fs.existsSync(metadataFile)) {
    metadata = JSON.parse(fs.readFileSync(metadataFile, 'utf-8'));
  }

  const files = fs.readdirSync(iconsDir);
  const slugs = files
    .filter(f => f.endsWith('.js'))
    .map(f => f.replace('.js', ''))
    .sort();

  const registry = [];
  const modules = {};

  for (const slug of slugs) {
    const name = toPascalCase(slug);
    const meta = metadata[slug];
    
    let category = 'Uncategorized';
    let tags = [];
    
    if (meta && meta.categories && meta.categories.length > 0) {
      category = toTitleCase(meta.categories[0]);
      tags = meta.categories.slice(1);
    }
    
    registry.push({
      name,
      slug,
      library: 'material-symbols',
      category,
      tags
    });
    
    modules[slug] = `() => import('@material-symbols-svg/react/icons/${slug}')`;
  }

  const registryContent = `import type { IconMeta } from './types';

// Auto-generated by scripts/generate-icons.mjs
// Do not edit manually.

export const ICON_REGISTRY: IconMeta[] = ${JSON.stringify(registry, null, 2)};

// Build a fast search index — keyed by slug for O(1) lookup
export const ICON_INDEX = new Map<string, IconMeta>(
  ICON_REGISTRY.map(icon => [icon.slug, icon])
);

// Get all unique categories
export const ICON_CATEGORIES = ['All', ...Array.from(new Set(ICON_REGISTRY.map(i => i.category))).sort()];
`;

  fs.writeFileSync(registryFile, registryContent, 'utf-8');

  // For loader, we need to inject the ICON_MODULES.
  const loaderParts = [
    `import type React from 'react';`,
    ``,
    `type IconComponent = React.ComponentType<{ size?: number; color?: string; className?: string; style?: React.CSSProperties }>;`,
    ``,
    `const iconCache = new Map<string, IconComponent>();`,
    ``,
    `/**`,
    ` * Static import map — every path is a string literal so Webpack can build`,
    ` * a chunk manifest for each icon at compile time.`,
    ` *`,
    ` * Auto-generated by scripts/generate-icons.mjs`,
    ` */`,
    `const ICON_MODULES: Record<string, () => Promise<Record<string, unknown>>> = {`
  ];
  
  for (const slug of slugs) {
    loaderParts.push(`  '${slug}': ${modules[slug]},`);
  }
  
  loaderParts.push(
    `};`,
    ``,
    `export async function loadIconComponent(`,
    `  name: string,`,
    `  library: 'material-symbols'`,
    `): Promise<IconComponent | null> {`,
    `  const cacheKey = \`\${library}:\${name}\`;`,
    `  if (iconCache.has(cacheKey)) return iconCache.get(cacheKey)!;`,
    ``,
    `  try {`,
    `    const slug = name`,
    `      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')`,
    `      .toLowerCase();`,
    ``,
    `    const loader = ICON_MODULES[slug];`,
    `    if (!loader) {`,
    `      console.error(\`[IconLoader] No module entry for slug: "\${slug}" (icon: \${name})\`);`,
    `      return null;`,
    `    }`,
    ``,
    `    const mod = await loader();`,
    `    const exportName = \`\${name}W400\`;`,
    `    const component = (mod as Record<string, unknown>)[exportName] as IconComponent | undefined;`,
    `    if (!component) {`,
    `      console.error(\`[IconLoader] Export "\${exportName}" not found in module for "\${slug}"\`);`,
    `      return null;`,
    `    }`,
    `    iconCache.set(cacheKey, component);`,
    `    return component;`,
    `  } catch (err) {`,
    `    console.error(\`[IconLoader] Failed to load icon: \${name} from \${library}\`, err);`,
    `    return null;`,
    `  }`,
    `}`,
    ``,
    `export function getIconComponentSync(name: string, library: 'material-symbols'): IconComponent | null {`,
    `  return iconCache.get(\`\${library}:\${name}\`) ?? null;`,
    `}`,
    ``,
    `export async function preloadIconBatch(icons: Array<{ name: string; library: 'material-symbols' }>): Promise<void> {`,
    `  await Promise.allSettled(icons.map(({ name, library }) => loadIconComponent(name, library)));`,
    `}`
  );
  
  fs.writeFileSync(loaderFile, loaderParts.join('\n'), 'utf-8');

  console.log(`Successfully generated ${slugs.length} icons.`);
}

generate().catch(console.error);
